"""
Serving-time feature computation for the contrails web tool.

Rebuilds the canonical model feature vector for an ARBITRARY flight
specified as (origin airport, destination airport, departure time UTC,
aircraft ICAO type) — no process-model data required.

The two engineered features were reverse-validated against the training
shards (mean abs error 0.000 on sampled flights, 2026-08-18):

  night_score_full_0 = 100 * (1 - mean(max(0, sin(sun_altitude))))
      over NB=30 great-circle waypoints (pyproj Geod.npts, WGS84) with
      waypoint times linearly interpolated departure → arrival, sun
      altitude from pyephem at each (lon, lat, t).

  land_score = 100 * min(1, geodesic_km(line ∩ land) / geodesic_km(line))
      where line is the STRAIGHT lon/lat segment origin → destination
      (not the great circle — matches Silas's pipeline) and land is the
      unary union of Natural Earth 110m admin-0 country polygons.

Arrival time is estimated from great-circle distance with the linear
fit  duration_h = 0.356 + 1.148 * (km / 1000)   (R²=0.988 on shard data).

Cyclic encodings match experiments/common.py::add_features
exactly (integer truncation of departure hour included).
"""

from __future__ import annotations

import json
import math
from datetime import datetime, timedelta
from pathlib import Path

import ephem
import numpy as np
from pyproj import Geod
from shapely import wkb as shapely_wkb

ASSETS = Path(__file__).parent / "assets"

NB_WAYPOINTS = 30
DURATION_INTERCEPT_H = 0.356
DURATION_SLOPE_H_PER_KM = 1.148e-3

MODEL_FEATS = [
    "total_flight_distance_km",
    "day_sin", "day_cos",
    "start_hour_sin", "start_hour_cos",
    "OriginLat", "OriginLon_sin", "OriginLon_cos",
    "DestinationLat", "DestinationLon_sin", "DestinationLon_cos",
    "land_score",
    "night_score_full_0",
    "aircraft_type_icao",
]

_geod = Geod(ellps="WGS84")
_observer = ephem.Observer()
_sun = ephem.Sun()

_airports = None
_land = None


def airports() -> dict:
    """{IATA: {lat, lon, tz, name}} — generated by export_assets.py."""
    global _airports
    if _airports is None:
        with open(ASSETS / "airports.json") as f:
            _airports = json.load(f)
    return _airports


def _land_union():
    global _land
    if _land is None:
        _land = shapely_wkb.loads((ASSETS / "land_union.wkb").read_bytes())
    return _land


def great_circle_km(olon, olat, dlon, dlat) -> float:
    _, _, dist_m = _geod.inv(olon, olat, dlon, dlat)
    return dist_m / 1e3


def estimate_duration_h(distance_km: float) -> float:
    return DURATION_INTERCEPT_H + DURATION_SLOPE_H_PER_KM * distance_km


def night_score(olon, olat, dlon, dlat,
                dep_utc: datetime, arr_utc: datetime) -> float:
    pts = np.array(_geod.npts(olon, olat, dlon, dlat, NB_WAYPOINTS))
    span = (arr_utc - dep_utc).total_seconds()
    sins = []
    for i, (lon, lat) in enumerate(pts):
        t = dep_utc + timedelta(seconds=span * i / (NB_WAYPOINTS - 1))
        _observer.long = lon * ephem.degree
        _observer.lat = lat * ephem.degree
        _observer.date = t.strftime("%Y-%m-%d %H:%M:%S")
        _sun.compute(_observer)
        sins.append(max(0.0, math.sin(_sun.alt)))
    return 100.0 * (1.0 - float(np.mean(sins)))


def land_score(olon, olat, dlon, dlat) -> float:
    from shapely.geometry import LineString
    line = LineString([(olon, olat), (dlon, dlat)])
    total_km = _geod.geometry_length(line) / 1e3
    if total_km <= 0:
        return 0.0
    inter = line.intersection(_land_union())
    land_km = 0.0 if inter.is_empty else _geod.geometry_length(inter) / 1e3
    return 100.0 * min(1.0, land_km / total_km)


def build_features(origin_iata: str, dest_iata: str, dep_utc: datetime,
                   aircraft_icao: str) -> dict:
    """Return the 14 model feature values for one flight."""
    ap = airports()
    o, d = ap[origin_iata.upper()], ap[dest_iata.upper()]
    olat, olon = o["lat"], o["lon"]
    dlat, dlon = d["lat"], d["lon"]

    dist_km = great_circle_km(olon, olat, dlon, dlat)
    arr_utc = dep_utc + timedelta(hours=estimate_duration_h(dist_km))

    doy = float(dep_utc.timetuple().tm_yday)
    hour = float(dep_utc.hour)          # integer-truncated, as in training

    return {
        "total_flight_distance_km": dist_km,
        "day_sin": math.sin(2 * math.pi * doy / 365),
        "day_cos": math.cos(2 * math.pi * doy / 365),
        "start_hour_sin": math.sin(2 * math.pi * hour / 24),
        "start_hour_cos": math.cos(2 * math.pi * hour / 24),
        "OriginLat": olat,
        "OriginLon_sin": math.sin(2 * math.pi * olon / 360),
        "OriginLon_cos": math.cos(2 * math.pi * olon / 360),
        "DestinationLat": dlat,
        "DestinationLon_sin": math.sin(2 * math.pi * dlon / 360),
        "DestinationLon_cos": math.cos(2 * math.pi * dlon / 360),
        "land_score": land_score(olon, olat, dlon, dlat),
        "night_score_full_0": night_score(olon, olat, dlon, dlat,
                                          dep_utc, arr_utc),
        "aircraft_type_icao": aircraft_icao.upper(),
    }
